// Shared HTTP wrappers for the staging-mode Playwright specs
// (stripe-roundtrip, gift-roundtrip, listen-roundtrip).
//
// Two access styles coexist by intent:
//   - `regenerateGiftClaim` takes Playwright's `APIRequestContext` so the
//     gift spec can reuse the test fixture's `extraHTTPHeaders` (CF Access
//     headers attach automatically).
//   - `issueMagicLink` + the Sanity poll helpers use native `fetch` /
//     `@sanity/client` because the listen spec calls them outside of a
//     Playwright `test.use({ extraHTTPHeaders })` scope.
import type { APIRequestContext } from "@playwright/test";
import { createClient, type SanityClient } from "@sanity/client";

export const STAGING_URL =
  process.env.STAGING_URL ?? "https://staging.withjosephine.com";

const REGENERATE_GIFT_CLAIM_PATH = "/api/internal/gift-claim-regenerate";

export function requireStagingEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(
      `[stagingApi] env ${name} is required for this spec — source .env.staging first.`,
    );
  }
  return value;
}

export function accessHeaders(): Record<string, string> {
  return {
    "CF-Access-Client-Id": requireStagingEnv("CF_ACCESS_CLIENT_ID"),
    "CF-Access-Client-Secret": requireStagingEnv("CF_ACCESS_CLIENT_SECRET"),
  };
}

export type RegenerateGiftClaimResponse = {
  outcome: "regenerated";
  to: string;
  deliveryMethod: "self_send" | "scheduled";
  resendDispatched: boolean;
  claimUrl: string;
};

export async function regenerateGiftClaim(
  request: APIRequestContext,
  submissionId: string,
  secret: string,
  options: { pollMs?: number; timeoutMs?: number } = {},
): Promise<RegenerateGiftClaimResponse> {
  const pollMs = options.pollMs ?? 3_000;
  const timeoutMs = options.timeoutMs ?? 120_000;
  const deadline = Date.now() + timeoutMs;
  let lastStatus = 0;
  let lastBody = "";
  while (Date.now() < deadline) {
    const response = await request.post(REGENERATE_GIFT_CLAIM_PATH, {
      headers: { "x-do-secret": secret, "content-type": "application/json" },
      data: { submissionId },
    });
    if (response.ok()) {
      return (await response.json()) as RegenerateGiftClaimResponse;
    }
    lastStatus = response.status();
    lastBody = await response.text();
    if (lastStatus !== 404) {
      break;
    }
    await new Promise((resolve) => setTimeout(resolve, pollMs));
  }
  throw new Error(
    `regenerateGiftClaim failed: status=${lastStatus} body=${lastBody.slice(0, 200)}`,
  );
}

/**
 * Polls staging Sanity for a submission keyed by the Stripe Checkout
 * `session.id`. The Stripe Payment Link success_url is configured as
 * `/thank-you/<readingSlug>?sessionId={CHECKOUT_SESSION_ID}` — the route
 * param is the reading slug, NOT the submission id. The real id is
 * generated by the Stripe webhook handler and mirrored to Sanity with
 * `stripeSessionId` populated.
 */
export async function findSubmissionIdByStripeSessionId(
  stripeSessionId: string,
  options: { timeoutMs?: number; pollIntervalMs?: number } = {},
): Promise<string> {
  const timeoutMs = options.timeoutMs ?? 120_000;
  const pollIntervalMs = options.pollIntervalMs ?? 2_500;
  const client = getStagingSanityReadClient();
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const result = await client.fetch<{ _id: string } | null>(
      `*[_type == "submission" && stripeSessionId == $sessionId][0]{ _id }`,
      { sessionId: stripeSessionId },
    );
    if (result?._id) return result._id;
    await sleep(pollIntervalMs);
  }
  throw new Error(
    `findSubmissionIdByStripeSessionId: no submission for ${stripeSessionId} within ${timeoutMs}ms`,
  );
}

/**
 * Calls `/api/internal/issue-magic-link` to obtain a raw magic-link token
 * for `email` without firing Resend. Auth: `x-admin-token` from
 * `ADMIN_API_KEY` in `.env.staging`.
 */
export async function issueMagicLink(email: string): Promise<{
  token: string;
  verifyUrl: string;
  expiresAt: number;
}> {
  const adminToken = requireStagingEnv("ADMIN_API_KEY");
  const response = await fetch(`${STAGING_URL}/api/internal/issue-magic-link`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-admin-token": adminToken,
      ...accessHeaders(),
    },
    body: JSON.stringify({ email }),
  });
  if (!response.ok) {
    throw new Error(
      `[stagingApi.issueMagicLink] ${response.status} ${response.statusText} for ${email}`,
    );
  }
  return (await response.json()) as {
    token: string;
    verifyUrl: string;
    expiresAt: number;
  };
}

/**
 * Polls staging Sanity for `listenedAt` on a submission. Used to verify the
 * fire-and-forget mirror after the spec fetches `/api/listen/[id]/audio`.
 */
export async function pollSanityListenedAt(
  submissionId: string,
  options: { timeoutMs?: number; pollIntervalMs?: number } = {},
): Promise<string | null> {
  const timeoutMs = options.timeoutMs ?? 15_000;
  const pollIntervalMs = options.pollIntervalMs ?? 1000;
  const client = getStagingSanityReadClient();
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const result = await client.fetch<{ listenedAt: string | null } | null>(
      `*[_type == "submission" && _id == $id][0]{ listenedAt }`,
      { id: submissionId },
    );
    if (result?.listenedAt) {
      return result.listenedAt;
    }
    await sleep(pollIntervalMs);
  }
  return null;
}

/**
 * Polls staging Sanity until the submission's `status` field reads `paid`
 * (the Stripe webhook is fire-and-forget after thank-you lands).
 */
export async function pollUntilPaid(
  submissionId: string,
  options: { timeoutMs?: number; pollIntervalMs?: number } = {},
): Promise<boolean> {
  const timeoutMs = options.timeoutMs ?? 30_000;
  const pollIntervalMs = options.pollIntervalMs ?? 1500;
  const client = getStagingSanityReadClient();
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const result = await client.fetch<{ status: string | null } | null>(
      `*[_type == "submission" && _id == $id][0]{ status }`,
      { id: submissionId },
    );
    if (result?.status === "paid") return true;
    await sleep(pollIntervalMs);
  }
  return false;
}

let cachedReadClient: SanityClient | null = null;

function getStagingSanityReadClient(): SanityClient {
  if (cachedReadClient) return cachedReadClient;
  const token =
    process.env.SANITY_E2E_READ_TOKEN ?? process.env.SANITY_READ_TOKEN;
  if (!token) {
    throw new Error(
      "[stagingApi] SANITY_E2E_READ_TOKEN or SANITY_READ_TOKEN required for Sanity polling.",
    );
  }
  cachedReadClient = createClient({
    projectId: requireStagingEnv("NEXT_PUBLIC_SANITY_PROJECT_ID"),
    dataset: requireStagingEnv("NEXT_PUBLIC_SANITY_DATASET"),
    apiVersion: "2025-01-01",
    token,
    useCdn: false,
  });
  return cachedReadClient;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
