// Helpers for talking to internal staging endpoints from Playwright specs.
//
// `regenerateGiftClaim` is thin over Playwright's `request` context so the
// spec stays declarative (CF Access service-token headers attach via the
// test fixture's `extraHTTPHeaders`). `findGiftSubmissionIdByEmail` reaches
// into staging Sanity directly via `@sanity/client` because the lookup is
// the spec's only way to recover the server-generated submission id — the
// post-Stripe `/thank-you/[readingId]` URL path carries the reading slug,
// not the submission id.
import type { APIRequestContext } from "@playwright/test";
import { createClient, type SanityClient } from "@sanity/client";

const REGENERATE_GIFT_CLAIM_PATH = "/api/internal/gift-claim-regenerate";

export type RegenerateGiftClaimResponse = {
  outcome: "regenerated";
  to: string;
  deliveryMethod: "self_send" | "scheduled";
  resendDispatched: boolean;
  claimUrl: string;
};

export async function regenerateGiftClaim(
  request: APIRequestContext,
  submissionId: string,
  secret: string,
  options: { pollMs?: number; timeoutMs?: number } = {},
): Promise<RegenerateGiftClaimResponse> {
  const pollMs = options.pollMs ?? 3_000;
  const timeoutMs = options.timeoutMs ?? 120_000;
  const deadline = Date.now() + timeoutMs;
  let lastStatus = 0;
  let lastBody = "";
  while (Date.now() < deadline) {
    const response = await request.post(REGENERATE_GIFT_CLAIM_PATH, {
      headers: { "x-do-secret": secret, "content-type": "application/json" },
      data: { submissionId },
    });
    if (response.ok()) {
      return (await response.json()) as RegenerateGiftClaimResponse;
    }
    lastStatus = response.status();
    lastBody = await response.text();
    // 404 (submission not found yet) is the expected transient. Any other
    // status is fatal — surface immediately so the spec doesn't waste budget.
    if (lastStatus !== 404) {
      break;
    }
    await new Promise((resolve) => setTimeout(resolve, pollMs));
  }
  throw new Error(
    `regenerateGiftClaim failed: status=${lastStatus} body=${lastBody.slice(0, 200)}`,
  );
}

function requireStagingEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(
      `[stagingApi] env ${name} is required for this spec — source .env.staging first.`,
    );
  }
  return value;
}

let cachedReadClient: SanityClient | null = null;

function getStagingSanityReadClient(): SanityClient {
  if (cachedReadClient) return cachedReadClient;
  const token =
    process.env.SANITY_E2E_READ_TOKEN ?? process.env.SANITY_READ_TOKEN;
  if (!token) {
    throw new Error(
      "[stagingApi] SANITY_E2E_READ_TOKEN or SANITY_READ_TOKEN required for Sanity polling.",
    );
  }
  cachedReadClient = createClient({
    projectId: requireStagingEnv("NEXT_PUBLIC_SANITY_PROJECT_ID"),
    dataset: requireStagingEnv("NEXT_PUBLIC_SANITY_DATASET"),
    apiVersion: "2025-01-01",
    token,
    useCdn: false,
  });
  return cachedReadClient;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Polls staging Sanity for a submission keyed by the Stripe Checkout
 * `session.id`. The Stripe Payment Link success_url is configured as
 * `/thank-you/<readingSlug>?sessionId={CHECKOUT_SESSION_ID}` — the route
 * param is the reading slug, NOT the submission id. The real id is
 * generated by the Stripe webhook handler and mirrored to Sanity with
 * `stripeSessionId` populated.
 *
 * Returns the submission `_id` once Sanity reports it, or throws on timeout.
 */
export async function findSubmissionIdByStripeSessionId(
  stripeSessionId: string,
  options: { timeoutMs?: number; pollIntervalMs?: number } = {},
): Promise<string> {
  const timeoutMs = options.timeoutMs ?? 120_000;
  const pollIntervalMs = options.pollIntervalMs ?? 2_500;
  const client = getStagingSanityReadClient();
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const result = await client.fetch<{ _id: string } | null>(
      `*[_type == "submission" && stripeSessionId == $sessionId][0]{ _id }`,
      { sessionId: stripeSessionId },
    );
    if (result?._id) return result._id;
    await sleep(pollIntervalMs);
  }
  throw new Error(
    `findSubmissionIdByStripeSessionId: no submission for ${stripeSessionId} within ${timeoutMs}ms`,
  );
}
