import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const INPUT = resolve(ROOT, "studio/preview-input.css");
const OUTPUT_CSS = resolve(ROOT, "studio/.generated/preview-styles.css");
const OUTPUT_TS = resolve(ROOT, "studio/.generated/preview-styles.ts");
const TAILWIND_BIN = resolve(ROOT, "node_modules/.bin/tailwindcss");

mkdirSync(dirname(OUTPUT_CSS), { recursive: true });

execFileSync(TAILWIND_BIN, ["--input", INPUT, "--output", OUTPUT_CSS, "--minify"], {
  cwd: ROOT,
  stdio: "inherit",
});

const css = readFileSync(OUTPUT_CSS, "utf8");
writeFileSync(
  OUTPUT_TS,
  `// AUTO-GENERATED by scripts/build-studio-preview-css.mts — do not edit.\nexport const PREVIEW_STYLES = ${JSON.stringify(css)};\n`,
  "utf8",
);
