/**
 * Safely seed SEO fields (metaTitle, metaDescription) on Sanity documents.
 *
 * Guarantees — by design, never clobbers server edits:
 *   - Uses patch().setIfMissing() at the FIELD level (not document level)
 *   - Any SEO field a human has already edited in Studio is SKIPPED
 *   - Missing documents are logged as SKIP, not errors
 *   - No createOrReplace, no set() — only setIfMissing()
 *
 * Pre-flight:
 *   Before any writes, prints the current SEO state of every target
 *   document so you can see exactly what is about to change.
 *
 * Run:
 *   cd www
 *   set -a && source .env.local && set +a && pnpm tsx scripts/seed-seo.ts
 *
 * Copy source:
 *   Generated by a 3-agent brand/SEO council (see Plans/seo-seed-prd.md).
 *   To rewrite, edit COPY below and re-run. Fields a human has since
 *   edited in Studio will NOT be overwritten — clear them in Studio first.
 */
import { createClient, type SanityClient } from "@sanity/client";
import type { SanitySeo } from "../src/lib/sanity/types";

const client: SanityClient = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || "production",
  apiVersion: "2025-01-01",
  useCdn: false,
  token: process.env.SANITY_WRITE_TOKEN,
});

type SeoCopy = { metaTitle: string; metaDescription: string };

/** Copy generated by brand/SEO council. All values validated against
 *  brand/STYLE_GUIDE.md §9 (banned-word filter) and char limits
 *  (metaTitle ≤60, metaDescription ≤160). */
const COPY = {
  landingPage: {
    metaTitle: "Josephine — Astrology & Akashic Record Readings",
    metaDescription:
      "Your soul has patterns. Your chart reveals them. Your records explain why. Personal astrology and Akashic Record readings delivered as voice notes and PDFs.",
  },
  "reading-soul-blueprint": {
    metaTitle: "Soul Blueprint Reading | Josephine — $179",
    metaDescription:
      "The complete picture. Your birth chart, Akashic Records, and card pulls woven into one deeply personal reading. Voice note and PDF, delivered in 7 days.",
  },
  "reading-birth-chart": {
    metaTitle: "Birth Chart Reading | Josephine — $99",
    metaDescription:
      "What the stars already said about you. Core themes, natural gifts, and current patterns — written and spoken just for you. Delivered in 7 days.",
  },
  "reading-akashic-record": {
    metaTitle: "Akashic Record Reading | Josephine — $79",
    metaDescription:
      "An Akashic Record reading that feels specific to you. Josephine delivers a voice note and PDF within 7 days. For when you're ready to remember what you carry.",
  },
  bookingPage: {
    metaTitle: "Book a Reading — Josephine",
    metaDescription:
      "Choose your reading and share your details. Your voice note and PDF will be with you within 7 days. No call required — everything arrives when you're ready.",
  },
  thankYouPage: {
    metaTitle: "Thank You — Josephine",
    metaDescription:
      "Your reading is on its way. You'll receive a personal voice note and PDF within 7 days. In the meantime, there's nothing you need to do.",
  },
} satisfies Record<string, SeoCopy>;

/** Legal pages are fetched by slug, not by fixed `_id`. */
const LEGAL_COPY = {
  privacy: {
    metaTitle: "Privacy Policy — Josephine",
    metaDescription:
      "How Josephine Soul Readings handles your personal information. Plain language, no surprises. Your details stay yours.",
  },
  terms: {
    metaTitle: "Terms of Service — Josephine",
    metaDescription:
      "The terms that apply when you book a reading with Josephine. Written plainly so you know exactly what to expect.",
  },
  "refund-policy": {
    metaTitle: "Refund Policy — Josephine",
    metaDescription:
      "Clear refund terms for all Josephine readings. What's covered, what isn't, and how to reach out if something feels off.",
  },
} satisfies Record<string, SeoCopy>;

type TargetDoc = {
  id: string;
  label: string;
  copy: SeoCopy;
};

type ExistingSeo = Pick<SanitySeo, "metaTitle" | "metaDescription"> | null;

function truncate(value: string | undefined, max = 80): string {
  if (!value) return "<empty>";
  return value.length > max ? `${value.slice(0, max - 1)}…` : value;
}

async function resolveTargets(): Promise<TargetDoc[]> {
  // Singletons + readings: _id IS the COPY key. Readings get a friendlier label.
  const targets: TargetDoc[] = Object.entries(COPY).map(([id, copy]) => ({
    id,
    label: id.startsWith("reading-") ? `reading(${id.slice("reading-".length)})` : id,
    copy,
  }));

  // Resolve legalPage _ids by slug.
  const legalSlugs = Object.keys(LEGAL_COPY);
  const legalDocs = await client.fetch<Array<{ _id: string; slug: { current: string } }>>(
    `*[_type == "legalPage" && slug.current in $slugs]{ _id, slug }`,
    { slugs: legalSlugs },
  );
  const legalBySlug = new Map(legalDocs.map((d) => [d.slug?.current, d] as const));
  for (const slug of legalSlugs) {
    const doc = legalBySlug.get(slug);
    if (doc) {
      targets.push({
        id: doc._id,
        label: `legalPage(${slug})`,
        copy: LEGAL_COPY[slug as keyof typeof LEGAL_COPY],
      });
    } else {
      console.warn(`WARN  legalPage with slug "${slug}" not found on server — will be skipped.`);
    }
  }

  return targets;
}

async function preflight(targets: TargetDoc[]): Promise<Map<string, ExistingSeo>> {
  const ids = targets.map((t) => t.id);
  const docs = await client.fetch<Array<{ _id: string; seo?: ExistingSeo }>>(
    `*[_id in $ids]{ _id, seo }`,
    { ids },
  );
  const docsById = new Map(docs.map((d) => [d._id, d] as const));

  const state = new Map<string, ExistingSeo>();
  console.log("=== Pre-flight: current SEO state ===");
  for (const t of targets) {
    const doc = docsById.get(t.id);
    if (!doc) {
      console.log(`  ${t.label} (${t.id}): document not found on server`);
      state.set(t.id, null);
    } else {
      const seo = doc.seo ?? {};
      state.set(t.id, seo);
      console.log(
        `  ${t.label} (${t.id}): metaTitle=${truncate(seo.metaTitle ?? undefined)}, metaDescription=${truncate(seo.metaDescription ?? undefined)}`,
      );
    }
  }
  console.log("");
  return state;
}

/** Build a patch for a single target and report per-field outcome based on
 *  preflight state. Returns the patch to be committed in a transaction, or
 *  null if the document is missing on the server. */
function buildPatch(
  target: TargetDoc,
  existing: ExistingSeo,
): { patch: ReturnType<SanityClient["patch"]> | null; filled: number; skipped: number } {
  if (existing === null) {
    console.log(`SKIP  ${target.label}: document missing on server`);
    return { patch: null, filled: 0, skipped: 2 };
  }

  let filled = 0;
  let skipped = 0;

  // setIfMissing is idempotent — only writes fields that have no value.
  // Dotted paths are applied in patch order after the parent `seo: {}` is
  // ensured, so partial-SEO documents still get their missing field filled.
  const patch = client.patch(target.id).setIfMissing({ seo: {} }).setIfMissing({
    "seo.metaTitle": target.copy.metaTitle,
    "seo.metaDescription": target.copy.metaDescription,
  });

  if (existing.metaTitle) {
    console.log(`SKIP  ${target.label}.seo.metaTitle (already set)`);
    skipped++;
  } else {
    console.log(`FILL  ${target.label}.seo.metaTitle`);
    filled++;
  }
  if (existing.metaDescription) {
    console.log(`SKIP  ${target.label}.seo.metaDescription (already set)`);
    skipped++;
  } else {
    console.log(`FILL  ${target.label}.seo.metaDescription`);
    filled++;
  }

  return { patch, filled, skipped };
}

async function main(): Promise<void> {
  if (!process.env.NEXT_PUBLIC_SANITY_PROJECT_ID) {
    throw new Error("NEXT_PUBLIC_SANITY_PROJECT_ID is required");
  }
  if (!process.env.SANITY_WRITE_TOKEN) {
    throw new Error("SANITY_WRITE_TOKEN is required");
  }

  const targets = await resolveTargets();
  const state = await preflight(targets);

  console.log("=== Patching ===");
  const transaction = client.transaction();
  let totalFilled = 0;
  let totalSkipped = 0;
  let queued = 0;
  for (const target of targets) {
    const { patch, filled, skipped } = buildPatch(target, state.get(target.id) ?? null);
    totalFilled += filled;
    totalSkipped += skipped;
    if (patch) {
      transaction.patch(patch);
      queued++;
    }
  }

  if (queued > 0) {
    await transaction.commit();
  }

  console.log("");
  console.log(`Done. Filled ${totalFilled}, skipped ${totalSkipped}.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
