/**
 * Build-time script: fetches reading priceDisplay values from Sanity and writes
 * src/data/readings.generated.ts. The generated map is consumed by the Sanity
 * mappers as the runtime fallback when Sanity itself is unreachable, keeping
 * displayed prices in sync with the most recent successful build.
 *
 * Run via: pnpm sync-readings-from-sanity (or tsx scripts/sync-readings-from-sanity.ts)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createSanityBuildClient } from "./lib/sanity-build-client";

type ReadingPriceRow = {
  slug: string;
  priceDisplay: string;
};

async function fetchReadingPrices(): Promise<ReadingPriceRow[] | null> {
  const client = createSanityBuildClient();
  if (!client) {
    console.log("No NEXT_PUBLIC_SANITY_PROJECT_ID — skipping readings sync");
    return null;
  }
  console.log("Fetching reading prices from Sanity...");
  return client.fetch<ReadingPriceRow[]>(
    `*[_type == "reading" && defined(slug.current) && defined(priceDisplay)]
       | order(slug.current asc)
       { "slug": slug.current, priceDisplay }`,
  );
}

function generateModule(rows: ReadingPriceRow[]): string {
  const entries = rows
    .map((r) => `  ${JSON.stringify(r.slug)}: ${JSON.stringify(r.priceDisplay)},`)
    .join("\n");
  return `// AUTO-GENERATED by scripts/sync-readings-from-sanity.ts. Do not edit by hand.
// Last build's snapshot of reading priceDisplay values from Sanity, used as
// the runtime fallback when the live Sanity fetch fails. Editing prices here
// has no effect on the live site — edit the reading doc in Sanity Studio
// instead, then this file regenerates on the next build.

export const SANITY_READING_PRICES: Record<string, string> = {
${entries}
};
`;
}

async function main() {
  const rows = await fetchReadingPrices();
  if (!rows) return;

  if (rows.length === 0) {
    console.log("Sanity returned no reading docs — keeping existing generated file");
    return;
  }

  const filePath = resolve(import.meta.dirname, "../src/data/readings.generated.ts");
  const next = generateModule(rows);
  const existing = safeRead(filePath);
  if (existing === next) {
    console.log(`Up to date: ${filePath} (${rows.length} readings)`);
    return;
  }
  writeFileSync(filePath, next, "utf-8");
  console.log(`Wrote ${filePath} (${rows.length} readings)`);
}

function safeRead(path: string): string | null {
  try {
    return readFileSync(path, "utf-8");
  } catch {
    return null;
  }
}

main().catch((error) => {
  console.error("Failed to sync readings:", error);
  process.exit(1);
});
