import { defineField, defineType } from "sanity";

import { tokenReferenceField } from "../lib/tokenHelp";
import { slotValidation } from "../lib/validateSlots";

const validateGiftClaimSlots = slotValidation("emailGiftClaim");

export const emailGiftClaim = defineType({
  name: "emailGiftClaim",
  title: "Gift Claim → Recipient (First Send)",
  type: "document",
  description:
    "Sent to a gift recipient with a private link to claim and start their reading — this is the first time they hear from us. Reminders follow at 7, 14, and 21 days if they don't claim (see the Reminder template).",
  groups: [
    { name: "envelope", title: "Inbox preview" },
    { name: "header", title: "Brand header" },
    { name: "body", title: "Body" },
    { name: "card", title: "Reading card" },
    { name: "footer", title: "Sign-off & footer" },
    { name: "legacy", title: "Legacy fields (folded)" },
  ],
  fields: [
    tokenReferenceField("emailGiftClaim"),
    defineField({
      name: "subjectFirstSend",
      title: "Subject",
      type: "string",
      group: "envelope",
      initialValue: "A reading, waiting for you",
    }),
    defineField({
      name: "previewFirstSend",
      title: "Inbox preview",
      type: "string",
      group: "envelope",
      description:
        "The grey snippet shown next to the subject line in most inboxes. {purchaserFirstName} drops in the sender's name.",
      validation: validateGiftClaimSlots,
      initialValue: "{purchaserFirstName} has sent you a reading.",
    }),
    defineField({
      hidden: true,
      readOnly: true,
      name: "brandName",
      title: "Brand wordmark",
      type: "string",
      group: "header",
      initialValue: "Josephine",
    }),
    defineField({
      hidden: true,
      readOnly: true,
      name: "brandSubtitle",
      title: "Brand sub-line",
      type: "string",
      group: "header",
      initialValue: "Soul Readings",
    }),
    defineField({
      name: "heroLineFirstSend",
      title: "Hero line",
      type: "string",
      group: "header",
      initialValue: "A reading, for you",
    }),
    defineField({
      name: "body",
      title: "Body",
      type: "array",
      of: [{ type: "block", styles: [{ title: "Normal", value: "normal" }], lists: [] }],
      group: "body",
      description:
        'The full body of the email above the claim button. Use "{recipientName}", "{purchaserFirstName}", "{readingName}".',
      validation: validateGiftClaimSlots,
    }),
    defineField({
      name: "giftMessageLabel",
      title: "Gift-message label",
      type: "string",
      group: "body",
      description:
        "Header shown above the purchaser's personal note (only renders if they wrote one). {purchaserFirstName} sets the attribution.",
      validation: validateGiftClaimSlots,
      initialValue: "A note from {purchaserFirstName}",
    }),
    defineField({
      name: "claimButtonLabel",
      title: "Claim button label",
      type: "string",
      group: "body",
      initialValue: "OPEN YOUR GIFT",
    }),
    defineField({
      name: "claimUrlHelper",
      title: "Claim button helper",
      type: "array",
      of: [{ type: "block", styles: [{ title: "Normal", value: "normal" }], lists: [] }],
      group: "body",
      description: "Small text shown directly below the claim button.",
      validation: validateGiftClaimSlots,
    }),
    defineField({
      name: "cardLabel",
      title: "Reading card — label",
      type: "string",
      group: "card",
      initialValue: "The gift",
    }),
    defineField({
      name: "cardDeliveryLine",
      title: "Reading card — delivery line",
      type: "string",
      group: "card",
      initialValue: "Delivered within 7 days of your intake",
    }),
    defineField({
      hidden: true,
      readOnly: true,
      name: "signOffLine1",
      title: "Sign-off line 1",
      type: "string",
      group: "footer",
      initialValue: "With love,",
    }),
    defineField({
      hidden: true,
      readOnly: true,
      name: "signOffLine2",
      title: "Sign-off line 2",
      type: "string",
      group: "footer",
      initialValue: "Josephine ✦",
    }),
    defineField({
      hidden: true,
      readOnly: true,
      name: "footerDisclaimer",
      title: "Footer disclaimer",
      type: "string",
      group: "footer",
      initialValue: "Readings are offered for entertainment and personal reflection.",
    }),
    defineField({
      name: "greeting",
      title: "Greeting (legacy — folded into Body)",
      type: "string",
      group: "legacy",
      hidden: true,
      readOnly: true,
      validation: validateGiftClaimSlots,
      initialValue: "Hi {recipientName},",
    }),
    defineField({
      name: "bodyFirstSend",
      title: "Body — first send (legacy — folded into Body)",
      type: "array",
      of: [{ type: "block", styles: [{ title: "Normal", value: "normal" }], lists: [] }],
      group: "legacy",
      hidden: true,
      readOnly: true,
      validation: validateGiftClaimSlots,
    }),
    defineField({
      name: "subjectReminder",
      title: "Subject (reminder) — moved to Email — Gift Claim — Reminder",
      type: "string",
      group: "legacy",
      hidden: true,
      readOnly: true,
      initialValue: "A reading is still waiting for you",
    }),
    defineField({
      name: "previewReminder",
      title: "Inbox preview (reminder) — moved to Email — Gift Claim — Reminder",
      type: "string",
      group: "legacy",
      hidden: true,
      readOnly: true,
      validation: validateGiftClaimSlots,
      initialValue: "A small reminder about the reading {purchaserFirstName} sent you.",
    }),
    defineField({
      name: "heroLineReminder",
      title: "Hero line — reminder — moved to Email — Gift Claim — Reminder",
      type: "string",
      group: "legacy",
      hidden: true,
      readOnly: true,
      initialValue: "Still here, when you’re ready",
    }),
    defineField({
      name: "bodyReminder",
      title: "Body — reminder — moved to Email — Gift Claim — Reminder",
      type: "array",
      of: [{ type: "block", styles: [{ title: "Normal", value: "normal" }], lists: [] }],
      group: "legacy",
      hidden: true,
      readOnly: true,
      validation: validateGiftClaimSlots,
    }),
    defineField({
      name: "reminderContactLine",
      title: "Reminder — contact line — moved to Email — Gift Claim — Reminder",
      type: "array",
      of: [{ type: "block", styles: [{ title: "Normal", value: "normal" }], lists: [] }],
      group: "legacy",
      hidden: true,
      readOnly: true,
    }),
  ],
  preview: {
    prepare: () => ({ title: "Email — Gift Claim — First Send (to recipient)" }),
  },
});
