import { defineField, defineType } from "sanity";

export const listenPage = defineType({
  name: "listenPage",
  title: "Listen Page",
  type: "document",
  groups: [
    { name: "welcome", title: "Welcome ribbon" },
    { name: "delivered", title: "Delivered surface" },
    { name: "signIn", title: "Sign-in card" },
    { name: "checkEmail", title: "Check-email card" },
    { name: "rested", title: "Rested-link card" },
    { name: "throttled", title: "Throttled card" },
    { name: "assetTrouble", title: "Asset-trouble card" },
  ],
  fields: [
    defineField({
      name: "title",
      type: "string",
      hidden: true,
      initialValue: "Listen Page",
    }),
    defineField({
      name: "welcomeRibbon",
      title: "Welcome ribbon",
      type: "string",
      group: "welcome",
      description:
        "One-line ribbon shown above the reading H1 right after the customer confirms their email. Fades in then disappears.",
      initialValue: "Welcome back. You're signed in for the next seven days.",
    }),
    defineField({
      name: "deliveredHeading",
      title: "Reading heading",
      type: "string",
      group: "delivered",
      description: 'Shown when the reading is ready. Use "{readingName}" to insert the reading name.',
      initialValue: "Your {readingName} is ready",
    }),
    defineField({
      name: "deliveredSubheading",
      title: "Reading subheading",
      type: "string",
      group: "delivered",
      initialValue: "Best with headphones, somewhere quiet.",
    }),
    defineField({
      name: "voiceNoteLabel",
      title: "Voice-note section label",
      type: "string",
      group: "delivered",
      initialValue: "Voice note",
    }),
    defineField({
      name: "pdfLabel",
      title: "PDF section label",
      type: "string",
      group: "delivered",
      initialValue: "Supporting PDF",
    }),
    defineField({
      name: "pdfButtonLabel",
      title: "PDF download button label",
      type: "string",
      group: "delivered",
      initialValue: "Download PDF",
    }),
    defineField({
      name: "closerLine1",
      title: "Closing line 1",
      type: "text",
      rows: 2,
      group: "delivered",
      initialValue:
        "If anything you hear sits hard, or if a question opens up after, please write to me. I'd rather know than not.",
    }),
    defineField({
      name: "closerLine2",
      title: "Closing line 2 (sign-off)",
      type: "string",
      group: "delivered",
      initialValue: "With love, Josephine ✦",
    }),
    defineField({
      name: "signInHeading",
      title: "Sign-in heading",
      type: "string",
      group: "signIn",
      initialValue: "Welcome back",
    }),
    defineField({
      name: "signInBody",
      title: "Sign-in body",
      type: "text",
      rows: 3,
      group: "signIn",
      initialValue:
        "Tell us the email you used to book, and we'll send a fresh link to open your reading.",
    }),
    defineField({
      name: "signInButtonLabel",
      title: "Sign-in button label",
      type: "string",
      group: "signIn",
      initialValue: "Send me a link",
    }),
    defineField({
      name: "signInFootnote",
      title: "Sign-in italic footnote",
      type: "string",
      group: "signIn",
      initialValue: "Your reading is still here, exactly as it was.",
    }),
    defineField({
      name: "checkEmailHeading",
      title: "Check-email heading",
      type: "string",
      group: "checkEmail",
      initialValue: "Check your email",
    }),
    defineField({
      name: "checkEmailBody",
      title: "Check-email body",
      type: "text",
      rows: 3,
      group: "checkEmail",
      initialValue:
        "If we have a reading on file for that email, a fresh link is on its way. It expires in twenty-four hours.",
    }),
    defineField({
      name: "checkEmailResendLabel",
      title: "Send-another link label",
      type: "string",
      group: "checkEmail",
      initialValue: "Send another",
    }),
    defineField({
      name: "restedHeading",
      title: "Rested-link heading",
      type: "string",
      group: "rested",
      initialValue: "This link has rested",
    }),
    defineField({
      name: "restedBody",
      title: "Rested-link body",
      type: "text",
      rows: 3,
      group: "rested",
      description:
        "Same copy fires for every failure mode by design (no information leak about whether the link was expired, mismatched, or never existed).",
      initialValue:
        "This link's already been opened — sometimes that's because you clicked it on another device. No problem — we'll send a fresh one.",
    }),
    defineField({
      name: "restedCtaLabel",
      title: "Rested-link CTA label",
      type: "string",
      group: "rested",
      initialValue: "Send me a fresh link",
    }),
    defineField({
      name: "throttledHeading",
      title: "Throttled heading",
      type: "string",
      group: "throttled",
      initialValue: "One moment",
    }),
    defineField({
      name: "throttledBody",
      title: "Throttled body",
      type: "text",
      rows: 3,
      group: "throttled",
      initialValue:
        "We've sent a few links already. Try again in a few minutes — or write to me directly and I'll sort it out.",
    }),
    defineField({
      name: "throttledMailtoLabel",
      title: "Throttled mailto link label",
      type: "string",
      group: "throttled",
      initialValue: "Write to Josephine",
    }),
    defineField({
      name: "throttledMailtoSubject",
      title: "Throttled mailto subject",
      type: "string",
      group: "throttled",
      initialValue: "Trouble opening my reading",
    }),
    defineField({
      name: "assetTroubleHeading",
      title: "Asset-trouble heading",
      type: "string",
      group: "assetTrouble",
      initialValue: "This page is taking a moment",
    }),
    defineField({
      name: "assetTroubleBody",
      title: "Asset-trouble body",
      type: "text",
      rows: 3,
      group: "assetTrouble",
      description:
        "Shown when the reading is owned by this account but the voice note or PDF isn't reachable from this page.",
      initialValue:
        "The reading is here — sometimes the connection isn't. Try again in a minute, or write to me and I'll make sure it reaches you.",
    }),
    defineField({
      name: "assetTroubleTryAgainLabel",
      title: "Asset-trouble try-again label",
      type: "string",
      group: "assetTrouble",
      initialValue: "Try again",
    }),
    defineField({
      name: "assetTroubleMailtoLabel",
      title: "Asset-trouble mailto link label",
      type: "string",
      group: "assetTrouble",
      initialValue: "Write to Josephine",
    }),
    defineField({
      name: "assetTroubleMailtoSubject",
      title: "Asset-trouble mailto subject",
      type: "string",
      group: "assetTrouble",
      initialValue: "Trouble opening my reading",
    }),
  ],
  preview: {
    prepare: () => ({ title: "Listen Page" }),
  },
});
