// AUTO-GENERATED by scripts/sync-readings-from-sanity.ts. Do not edit by hand.
// Last build's snapshot of reading priceDisplay values from Sanity, used as
// the runtime fallback when the live Sanity fetch fails. Editing prices here
// has no effect on the live site — edit the reading doc in Sanity Studio
// instead, then this file regenerates on the next build.

export const SANITY_READING_PRICES: Record<string, string> = {
  "akashic-record": "$89",
  "birth-chart": "$89",
  "soul-blueprint": "$129",
};
